// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4c81d17e8de07f650cddf73ce751ba8d)
declare namespace Cloudflare {
	interface Env {
		MASTERMIND_GAMES: DurableObjectNamespace;
	}
}
interface Env extends Cloudflare.Env {}
